### ISSUE TITLE
Authentication with acquire_token_with_username_password

### ISSUE THREAD

**Issue by apsamudra** [AzureAD/azure-activedirectory-library-for-python#50] opened 2016-09-30 13:45 UTC
The acquire_token_with_username_password functionality does not perform as expected. The token returned with the current function returns 403 errors. This can be fixed by setting client_secret in 
Oauth parameters [at](https://github.com/AzureAD/azure-activedirectory-library-for-python/blob/dev/adal/token_request.py#L176)

This is described in 
http://stackoverflow.com/questions/32341877/cant-get-client-credentials-access-token-to-authorize-power-bi

for node and also works for python

**Comment by rayluo** [comment] 2016-10-07 18:36
This is a somewhat complicated topic. A short comment is that the acquire_token_with_username_password() was designed to NOT take the client_secret parameter. You can refer to the "No web sites/confidential clients" section in [this post](http://www.cloudidentity.com/blog/2014/07/08/using-adal-net-to-authenticate-users-via-usernamepassword/).

In fact, we recommend developers to [avoid using username/password](http://stackoverflow.com/a/28597758/728675). You can read more about all the different [authentication scenarios](https://azure.microsoft.com/en-us/documentation/articles/active-directory-authentication-scenarios/) and see which one works for you better.

**Comment by Li-ReDBox** [comment] 2016-10-10 23:33
Two things:
1. the library is broken: missing a required parameter;
2. some applications just cannot do a proper authentication at the moment. I know one for sure is Dynamics Online, which has no way to call it with client_id and client_secret. We have to use delegation to hack through.

**Comment by scottp-dpaw** [comment] 2016-10-11 06:43
Made a fork with a preliminary fix [here](https://github.com/scottp-dpaw/azure-activedirectory-library-for-python/tree/passwordauth). I get that Microsoft has good reasons to dissuade people from using username/password auth for the majority of use cases, but on the surface it looks like the response was to fully implement the feature in the REST API, then provide a method in the bindings that _almost_ works, except intentionally missing a field so that basic use cases fail? Which... doesn't make a lot of sense.

In all seriousness, is there actually a case where you can use acquire_token_with_username_password _without_ a client_secret? Every simple token request I made crashed and burned with "AADSTS90014: The request body must contain the following parameter: 'client_secret or client_assertion'."

**Comment by aarsan** [comment] 2017-01-03 18:57
FYI, I changed my azure ad app from a web app to a native app and it now works without client_secret.

**Comment by bryan-nice** [comment] 2017-12-18 23:11
@rayluo you're not answering the question. It is better to be direct and help people get the answer they are looking for instead of posting a response that has nothing to do with the question.

**Comment by toyg** [comment] 2018-07-10 15:05
@aarsan how did you do that? It doesn't seem to be possible to change an application type from the azure control panel, and if you create a Native application you don't get the option to create keys - so you don't have a secret to pass.

Very, very frustrating from Microsoft. The only option seems to be forking and patching like @scottp-dpaw has done.

**Comment by rayluo** [comment] 2018-07-10 18:09
@toyg It is probably true that the [Azure Control Panel](https://portal.azure.com/) does not really provide a way to *change* the app type. I believe what @aarsan did was to create another app as the type "Native application" and then it would just work without needing to provide a client_secret. And then the current ADAL Python should just work.

**Comment by jsenich** [comment] 2019-07-23 19:53
Creating a Native application did not work for me. I still get the "AADSTS90014: The request body must contain the following parameter: 'client_secret or client_assertion'." error.

**Comment by abhidnya13** [comment] 2019-07-25 23:36
Hi @jsenich,

Can you confirm if the application Manifest has ` "allowPublicClient" ` value set to be true ?
You can find the application manifest by going to the application registration and selecting `Manifest` from the left blade.

- If this value is set as null , go to the `Authentication` label on the left blade of your application registration and look for an option to select default client type. Select yes in the question which says Treat application as a public client and save your changes. Confirm in the application Manifest if the value is now set to be true and try the flow again.

- If the value is set as true and you are still getting the same error, it is because you or the admins has not consented to the permissions requested for the application. Refer [this](https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-permissions-and-consent#types-of-consent) for more information on why you should consent. 
To summarize briefly, when you ask access to a particular resource, AAD is going to verify if user or admin has consented access to this resource. If not it is going to show a UI to ask for users consent or wait for an admin to consent if it requires admin consent. This requires an interactive flow. Username-password does not involve any UI and thus returns the error. So, if you try and run this application through an interactive flow like authorization code flow or device code flow and give the required consent, you can successfully run username password sample without any errors from the next time onwards. If any of the resource requires admin consent, you will have to wait until the admins gives his consent.

- On a side note, the error message is misleading and does not give the actual reason. Will try and give this feedback to the team.

Let me know if this works for you. Thanks

**Comment by jsenich** [comment] 2019-07-26 17:50
@abhidnya13 That worked for me. Thanks!

**Comment by jmprieur** [comment] 2019-09-05 12:53
@abhidnya13,  @rayluo  :  I think we can close this one?

**Comment by rayluo** [comment] 2019-09-05 18:12
This is historically a frequently asked question. It got [most comments](https://github.com/AzureAD/azure-activedirectory-library-for-python/issues?q=is%3Aissue+label%3Aquestion+sort%3Acomments-desc), literally.
Previously I've been hesitated to close these kind of educational conversations, at least not until we reorganize it into a dedicated wike page.
This time, I put that "all questions sorted by comments" link into [both the sidebar and the home page of our wiki](https://github.com/AzureAD/azure-activedirectory-library-for-python/wiki). Please let me know if you think we should do even more, such as dupliate that FAQ link to more noticeable places, such as the main README page of this repo.

**Closed by rayluo** 2019-09-05 18:12 UTC
Labels: question

**Comment by rayluo** [comment] 2021-04-09 15:25
Just want to share an update here. AAD has recently been changed to allow apps with `client_secret` to use Username Password auth. So we enable such usage pattern in [MSAL for Python 1.11+](https://github.com/AzureAD/microsoft-authentication-library-for-python/releases/tag/1.11.0). This [ADAL for Python library is not scheduled to receive any new changes](https://github.com/AzureAD/azure-activedirectory-library-for-python#readme). Please consider [migrate from ADAL Python to MSAL Python](https://docs.microsoft.com/en-us/azure/active-directory/develop/migrate-python-adal-msal).
