### ISSUE TITLE
Won't install in Azure App Service

### ISSUE THREAD

**Issue by aarsan** [AzureAD/azure-activedirectory-library-for-python#62] opened 2017-01-05 18:51 UTC
I can't tell exactly what is going on, but when I add 'adal' to my requirements.txt file in Azure Web App, it bombs out on the 'adal' install with the following:

    File "D:\home\site\wwwroot\env\lib\site-packages\pip\_vendor\pkg_resources.py", line 2583, in scan_list
        "Expected ',' or end-of-list in",line,"at",line[p:]
    ValueError: ("Expected ',' or end-of-list in", 'requests >=2.0.0,!=2.12.*', 'at', '*')

**Comment by yugangw-msft** [comment] 2017-01-05 18:55
Dupe of #61

**Closed by yugangw-msft** 2017-01-05 18:55 UTC
